### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by theofidry** [ksylvest/jquery-growl#20]
Would be nice to install it right away with it

**Comment by ksylvest** [comment]
@theofidry Can you explain what you mean?

**Comment by theofidry** [comment]
I mean publishing it as a npm package besides the bower package, since it's really easy and fast to do and that npm is nearly used as much as Bower for front dependencies.

Moreover a minified version would really be welcomed, since when you install a package like yours, it's really convenient to not have to manually minify it.

**Comment by ksylvest** [comment]
@theofidry Sounds great, can you look into doing a pull request with these features?

**Comment by theofidry** [comment]
Sorry for the late answer.

Yeah I can do the minified version check the Bower and npm packages very shortly. But you'll still have to publish the packages yourself since you're the maintainer.

**Comment by ksylvest** [comment]
Closing for now due to inactivity. If you are still interested please open a pull request.

**Comment by theofidry** [comment]
Yeah sorry, too busy for now :(
