### ISSUE TITLE
Using growl with Typescript

### ISSUE THREAD

**Issue by beuted** [ksylvest/jquery-growl#21]
It would be nice to have .ts.d for this, to be able to use it with typescript.

**Comment by ksylvest** [comment]
@beuted How is this generated? What's the use case exactly?

**Comment by ksylvest** [comment]
No answer so closing.

**Comment by beuted** [comment]
Sorry I was travelling, this is related to typescript, It allows you to "type" a js library when writing typescript so you can use the lib with the type-checking feature of TS.

From TS website :
*"When using an external JavaScript library, or new host API, you'll need to use a declaration file (.d.ts) to describe the shape of that library. This guide covers a few high-level concepts specific to writing definition files, then proceeds with a number of examples that show how to transcribe various concepts to their matching definition file descriptions."*
More info Here : http://www.typescriptlang.org/Handbook#writing-dts-files

**Comment by ksylvest** [comment]
@beuted Interesting. If you are interested in having this added please fork and put in a pull request. I'm not a TypeScript user (as you can see the library is a CoffeeScript library).

**Comment by donrolling** [comment]
I made a project real quick with a d.ts file in it. I probably should do a fork and a pull request, but what I did seemed fastest. Hope it is helpful. LMK if there's something additional that I should do.

https://github.com/donrolling/JQuery.Growl.TypeScript.Definition
