### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by praveenbm5** [ksylvest/jquery-growl#22]
Thanks for the wonderful plugin! It made my day easier!

However, the documentation is really sparse for this plugin. Please document all the settings.

Also, how can we make some notifications clear the past ones? I need some new notifications to clear past notifications before showing up and some to just follow the default behavior and display below the previous ones.

Thanks in advance!

**Comment by ksylvest** [comment]
Closing. Feel free to open a pull request with documentation improvements instead of an issue.
