### ISSUE TITLE
Add a "don't auto close" option

### ISSUE THREAD

**Issue by ocanzillon** [ksylvest/jquery-growl#23]
Duration is set by default to 3200. There is no way to prevent from automatically closing the growl dialog. It would be great to be able to do it, by setting duration to -1 for example.

**Comment by ocanzillon** [comment]
I committed a patch in my fork, but I'm don't know very well git, so I don't know if I have to do anything else to propose my change.

**Comment by ksylvest** [comment]
Have you tried using the 'static': when presenting? That should make them stick around.

**Comment by ocanzillon** [comment]
Oh yes, it works! Thanks a lot. This feature is clearly what I need.
This could be great if you could describe a little bit available options in your website. This would avoid this kind of stupid question ;-).

**Comment by ksylvest** [comment]
@ocanzillon Yeah, absolutely I'm just a bit overloaded with the projects. Would you be able to add some documentation to the `README.md` and submit a pull request?

**Comment by ocanzillon** [comment]
Sorry, I have the same problem as you: I'm also overloaded with work.
Moreover I don't know your component enough deeply.

2015-02-04 19:14 GMT+01:00 Kevin Sylvestre <notifications@github.com>:
