### ISSUE TITLE
 $growl.off is not a function

### ISSUE THREAD

**Issue by h1979pk** [ksylvest/jquery-growl#25]
getting  $growl.off is not a function and notices are not closing. Please help.

**Comment by ksylvest** [comment]
Please re-open if you can provide better steps to reproduce this bug. Otherwise, please review the sample page and ensure you are integrating the same way.

**Comment by h1979pk** [comment]
yes the only difference is im using jquery-1.11.0.min.js because 2.0.2 is conflicting with other functions of website.
