### ISSUE TITLE
option name `static` is js reserved keyword

### ISSUE THREAD

**Issue by jhargis** [ksylvest/jquery-growl#26]
I believe it may be bad form to use js reserved words as object properties such as  `static`.
I've noticed that the YUI compressor fails when it encounters the property in this form

```if (data.static === true)```

but can be overcome with dict notation

```data['static'] ```

output from the compressor looks like this
```
Failed, error was: ExternalTool: subprocess returned a non-success result code: 2, stdout=, stderr=[ERROR] in -
  1884:28:missing name after . operator
```
Since using a reserved word is technically permitted in ECMAScript 5 it IS legal, but it can be problematic in certain cases such as this.

see http://stackoverflow.com/questions/7022397/using-reserved-words-as-property-names-revisited#answer-18533285

I suspect changing it would be rather disruptive. Perhaps a warning ?  

thoughts?

**Comment by ksylvest** [comment]
Good catch. Didn't realize is was a reserved word. What do you think about using `fixed` as a replacement? Seems like a better option anyways.

**Comment by jhargis** [comment]
I like them both! Fixed slightly better just because it's shorter.  I'd suggest doing something like leaving `static` in and throwing a deprecation warning in console. Documenting it as a deprecated option and leaving it for a few releases before yanking it entirely.  That way everybody using the library will have time to update there code and hopefully recognize that it's going away.  Until such time as it is removed, both options have the same effect but the primary documentation focuses on the new name `fixed`.

cheers!

**Comment by ksylvest** [comment]
@jhargis Pull request here: https://github.com/ksylvest/jquery-growl/pull/27 

If you can confirm this looks correct I can do a new release (1.2.6).

**Comment by jhargis** [comment]
reviewed

**Comment by jhargis** [comment]
So responsive! thank you!  great plugin Kevin!

**Comment by ksylvest** [comment]
Thanks for finding.
