### ISSUE TITLE
Rails implementation doesn't work

### ISSUE THREAD

**Issue by ristovskiv** [ksylvest/jquery-growl#32]
I've tried to implement this in rails adding it like a gem file under the

    source 'https://rails-assets.org' do
      gem 'rails-assets-growl'
    end

but adding the lines in the manifest files application.js and applications.sass it seems that rails can't find files named 'growl' for both extensions .js and .css .

Am I doing something wrong? If that is the case then I deeply appologize.

**Comment by ristovskiv** [comment]
Ok so it appears that it doesn't support  .sass extension of the manifest file. When I've changed it to scss everything is fine.

**Comment by ksylvest** [comment]
@ristovskiv Which manifest file? The import syntax for Sass vs Scss is different:

**Sass**:
```sass
@import growl
```

**Scss**:
```scss
@import 'growl'
```

If it something else please feel free to re-open.
