### ISSUE TITLE
Setting Global Options?

### ISSUE THREAD

**Issue by HarryPehkonen** [ksylvest/jquery-growl#33]
Instead of having to specify the same option on all notifications, it would be nice to be able to set some global options in one place.  For example, `$.growl.options({duration: 5000})`.

**Comment by coworkingon-es** [comment]
Hi, I am looking for a way to change the duration. I understand  the way to do it is to put inside the growl options right? Like:   $.growl({title:"", message: "<%= rand(1 .. 150) %>&nbsp;<%= t('.users_watching') %>", location: "bl", duration: 6000 }); Thanks!

**Comment by ksylvest** [comment]
I believe this should be working now:

```javascript
Growl.settings.duration = 5000;
```
