### ISSUE TITLE
Delay+Duration

### ISSUE THREAD

**Issue by coworkingon-es** [ksylvest/jquery-growl#34]
Hi there,
Many many thanks for this plugin! This is exactly what I was looking for, it is so easy to use with Rails! . One thing: i would like the notification to appear with delay and more time, How should I do?
Many many thanks!!

**Comment by ksylvest** [comment]
Hi,

For doing a more time you can specify `{ delay: 5000 /* (time in milliseconds) */ }`. For delaying the presentation of the modal your best bet it to use the `setTimeout` javascript function designed for this purpose.
