### ISSUE TITLE
Accessibility/ARIA concerns

### ISSUE THREAD

**Issue by SethMusulin** [ksylvest/jquery-growl#38]
Thank you for this great plugin. I am currently adding some accessibility functionality to an application that uses this plugin and was wondering if you would be interested in a pull request that added the same to the plugin?

**Comment by ksylvest** [comment]
@SethMusulin I'm always interested in PRs. What's the accessibility functionality you are adding?

**Comment by SethMusulin** [comment]
Mainly adding the 'alert' role to the growl notification themselves. Currently (unless I have missed something entirely) a screen reader does not notify a user with disabilities that an alert has been shown.

**Comment by ksylvest** [comment]
@SethMusulin that sounds great - I don't have a lot of familiarity with screen readers - but think it'd be great to support them.

**Comment by SethMusulin** [comment]
Ok, Thanks. I will close issue and try to get a PR in soon.
