### ISSUE TITLE
Add support for messages occupying multiple regions.

### ISSUE THREAD

**Issue by danielson317** [ksylvest/jquery-growl#39]
I'm using the growl library to notify users for updates as well as errors. The updates always show in the bottom right (out of the way) and the errors show on the top left (in the way making sure the user can see them). It is common to output an update followed by an error. However instead of outputing one in the bottom right and the other on the top left it starts on the bottom then shift to the top before appending the error.

Is their any intention of supporting growls occupying multiple regions at the same time?

**Comment by ksylvest** [comment]
@danielson317 Sorry for the delay. Not at this time - but a PR adding support is welcome.

**Comment by mnigbur** [comment]
#45
