### ISSUE TITLE
Dismiss hides the notice but does not always remove it.

### ISSUE THREAD

**Issue by danielson317** [ksylvest/jquery-growl#40]
I'm using growl to display ajax update notices. So I growl before the ajax request then dismiss the notice inside the ajax request. The dismiss/remove does not actually work due to the callback parameter being required.

      var args = {
        title: 'Updating',
        message: 'Adding new item...',
        style: 'system',
        duration: 0,
        location: 'br',
        size: 'large'
      };
      var $growl = $.growl(args);
      $.get(url, data, function(response)
      {
        // Minimum display time of 2.6 seconds.
        setTimeout(function() {$growl.dismiss();}, 2600);
      }, 'json').error(ajaxErrorHandler);

I was able to fix this by calling `remove` instead of `dismiss` and then editing `remove` to look like:

    Growl.prototype.remove = function(callback) {
      this.$growl().remove();
      /** My new code **/
      if (callback == undefined)
      {
        return;
      }
      /** end new code **/
      return callback();
    };

Their must be a better way to do this but the return callback always fails causing the animation to fade out the notice but not clear the div tags causing the invisible divs to prevent sections of the page from being selected.

**Comment by ksylvest** [comment]
@danielson317 I made the callback parameter optional for dismiss. If you install the latest version it'll be included. Closing but feel free to re-open if it doesn't fix your issue.
