### ISSUE TITLE
bug in 1.3.4 -  Cannot set property 'Growl' of undefined

### ISSUE THREAD

**Issue by ido172** [ksylvest/jquery-growl#47]
The last commint has a bug:
https://github.com/ksylvest/jquery-growl/commit/0a673cbce45c18ab6e2d7d16f97bbdb030418db2#diff-b11a5d782842d456be48fc3932f5b1d5

in the last line of jquery.growl.js you did this change:
```javascript 
-}).call(this);
 +}).call(undefined); 
```
this causes a javascript error  'Cannot set property 'Growl' of undefined' in this line
```javascript 
this.Growl = Growl;
```

does not happen in 1.3.1

**Comment by gs-akhan** [comment]
This is crazy issue. I don't see any reason why this was even done .. 

@ksylvest  I can fix it

**Comment by ksylvest** [comment]
@ido172 fixed in 1.3.5

**Comment by schmunk42** [comment]
@ksylvest Could you also add a tag to the repository? We're using your repo via https://github.com/fxpio/composer-asset-plugin which relies on tags.

@francoispluchino Would there be a way for fxpio/cap to fix this in another way?

**Comment by francoispluchino** [comment]
@schmunk42 You can use the `@dev` flag in your dependency to use a version without tag (like `"npm-asset/jquery-growl": "^1.3.5@dev"`).

**Comment by ksylvest** [comment]
@schmunk42 tagged
